export const archetypes = [
    { key: '11', type: 'anrachy', subtext: '', color: '' },
    { key: '12', type: 'rockstar', subtext: '', color: '' },
    { key: '13', type: 'maverick leader', subtext: '', color: '' },
    { key: '14', type: 'trendsetter', subtext: '', color: '' },
    { key: '15', type: 'artisan', subtext: '', color: '' },
    { key: '16', type: 'provocateur', subtext: '', color: '' },
    { key: '17', type: 'quick-start', subtext: '', color: '' },
    { key: '21', type: 'catalyst', subtext: '', color: '' },
    { key: '22', type: 'drama', subtext: '', color: '' },
    { key: '23', type: 'peoples champion', subtext: '', color: '' },
    { key: '24', type: 'talent', subtext: '', color: '' },
    { key: '25', type: 'beloved', subtext: '', color: '' },
    { key: '26', type: 'intrigue', subtext: '', color: '' },
    { key: '27', type: 'orchestrator', subtext: '', color: '' },
    { key: '31', type: 'change agent', subtext: '', color: '' },
    { key: '32', type: 'ringleader', subtext: '', color: '' },
    { key: '33', type: 'aggressor', subtext: '', color: '' },
    { key: '34', type: 'maestro', subtext: '', color: '' },
    { key: '35', type: 'guardian', subtext: '', color: '' },
    { key: '36', type: 'mastermind', subtext: '', color: '' },
    { key: '37', type: 'defender', subtext: '', color: '' },
    { key: '41', type: 'avant-garde', subtext: '', color: '' },
    { key: '42', type: 'connoisseur', subtext: '', color: '' },
    { key: '43', type: 'victor', subtext: '', color: '' },
    { key: '44', type: 'imperial', subtext: '', color: '' },
    { key: '45', type: 'blue chip', subtext: '', color: '' },
    { key: '46', type: 'architect', subtext: '', color: '' },
    { key: '47', type: 'scholar', subtext: '', color: '' },
    { key: '51', type: 'evolutionary', subtext: '', color: '' },
    { key: '52', type: 'authentic', subtext: '', color: '' },
    { key: '53', type: 'gravitas', subtext: '', color: '' },
    { key: '54', type: 'diplomat', subtext: '', color: '' },
    { key: '55', type: 'old guard', subtext: '', color: '' },
    { key: '56', type: 'anchor', subtext: '', color: '' },
    { key: '57', type: 'good citizen', subtext: '', color: '' },
    { key: '61', type: 'secret weapon', subtext: '', color: '' },
    { key: '62', type: 'subtle touch', subtext: '', color: '' },
    { key: '63', type: 'veiled strength', subtext: '', color: '' },
    { key: '64', type: 'royal guard', subtext: '', color: '' },
    { key: '65', type: 'wise owl', subtext: '', color: '' },
    { key: '66', type: 'deadbolt', subtext: '', color: '' },
    { key: '67', type: 'archer', subtext: '', color: '' },
    { key: '71', type: 'composer', subtext: '', color: '' },
    { key: '72', type: 'coordinator', subtext: '', color: '' },
    { key: '73', type: 'ace', subtext: '', color: '' },
    { key: '74', type: 'editor-in-chief', subtext: '', color: '' },
    { key: '75', type: 'mediator', subtext: '', color: '' },
    { key: '76', type: 'detective', subtext: '', color: '' },
    { key: '77', type: 'control freak', subtext: '', color: '' }

]